"""Generates the pipeline config.yaml from the extracted information.

The defaults below are heuristics; anything under 'config:' in the dataset's prepare.yaml
is deep-merged on top, so per-dataset tuning never needs code changes.
"""
import copy
from pathlib import Path
from typing import Dict, List, Optional

import yaml

from .cameras import Camera
from .metadata import ImageMeta

GENERATED_HEADER = "# Generated by sfm_preprocess (tools/preprocess). Edit prepare.yaml and re-run instead of editing this file.\n"


def deep_merge(base: dict, extra: dict) -> dict:
    out = copy.deepcopy(base)
    for k, v in (extra or {}).items():
        out[k] = deep_merge(out[k], v) if isinstance(v, dict) and isinstance(out.get(k), dict) else copy.deepcopy(v)
    return out


def is_nadir(metas: List[ImageMeta]) -> bool:
    pitches = [m.gimbal_pitch for m in metas if m.gimbal_pitch is not None]
    return bool(pitches) and sum(pitches) / len(pitches) < -75.0


def build_config(
    metas: List[ImageMeta],
    cameras: List[Camera],
    image_camera: Dict[str, int],
    image_dir: str,
    trajectory_file: Optional[str],
    image_list: Optional[List[str]] = None,
    overrides: Optional[dict] = None,
) -> dict:
    n = len(metas)
    nadir = is_nadir(metas)
    max_dim = max(max(c.width, c.height) for c in cameras)

    cfg: dict = {"io": {"image_dir": image_dir, "output_dir": "out"}}
    if image_list is not None:
        cfg["io"]["images"] = image_list
    cfg["cameras"] = [
        {"id": c.id, "width": c.width, "height": c.height, "fx": round(c.fx, 3), "fy": round(c.fy, 3), "cx": round(c.cx, 3),
         "cy": round(c.cy, 3), "dist": [float(d) for d in c.dist]}
        for c in cameras
    ]
    cfg["default_camera"] = 0
    if len(cameras) > 1:
        cfg["image_cameras"] = {name: cid for name, cid in image_camera.items() if cid != 0}

    if trajectory_file:
        cfg["trajectory"] = {"source": "file", "file": trajectory_file}
        cfg["matching"] = {"mode": "trajectory", "search": "knn", "knn": min(12, max(1, n - 1))}
    else:
        cfg["matching"] = {"mode": "exhaustive"} if n <= 150 else {"mode": "sequential", "sequential_overlap": 15}

    if max_dim > 3000:
        cfg["features"] = {"max_image_dim": 2000}  # SIFT at reduced resolution, keypoints mapped back

    # Intrinsics from EXIF are approximate: refine distortion. Over flat nadir scenes the focal
    # length is not observable (focal / flying height ambiguity), so keep it fixed there.
    cfg["final"] = {"ba": {"refine_intrinsics": True, "refine_focal_length": not nadir}}
    cfg["ortho"] = {"enabled": nadir}
    return deep_merge(cfg, overrides or {})


def write_config(path: Path, cfg: dict, notes: List[str]) -> Path:
    """Writes config.yaml, unless a hand-written one exists (then config.generated.yaml)."""
    target = path
    if path.exists() and not path.read_text().startswith(GENERATED_HEADER):
        target = path.with_name("config.generated.yaml")
    with open(target, "w") as f:
        f.write(GENERATED_HEADER)
        for note in notes:
            f.write(f"# {note}\n")
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=None)
    return target
